const canvas=document.getElementById('weatherCanvas'),ctx=canvas.getContext('2d');
const ids=['stress','time','ambiguity','social','loss','incentives','confidence','delay'];
const biasDefs=[
{name:'Availability',calc:v=>.45*v.stress+.35*v.time+.25*v.loss,move:'Ask: what evidence is missing because it is not vivid?'},
{name:'Confirmation',calc:v=>.35*v.confidence+.35*v.incentives+.30*v.ambiguity,move:'Require one serious disconfirming explanation.'},
{name:'Herding',calc:v=>.65*v.social+.20*v.ambiguity+.15*v.time,move:'Separate popularity from evidence.'},
{name:'Loss aversion',calc:v=>.65*v.loss+.25*v.stress+.10*v.stakes,move:'Compare loss avoided with opportunity lost.'},
{name:'Overconfidence',calc:v=>.55*v.confidence+.25*(100-v.ambiguity)+.20*v.delay,move:'Widen the range and name what would change your mind.'},
{name:'Anchoring',calc:v=>.35*v.ambiguity+.30*v.time+.20*v.social+.15*v.confidence,move:'Generate an independent estimate before seeing the anchor.'},
{name:'Motivated reasoning',calc:v=>.55*v.incentives+.25*v.confidence+.20*v.loss,move:'Make the incentive visible before evaluating evidence.'},
{name:'Status quo',calc:v=>.35*v.loss+.30*v.ambiguity+.20*v.delay+.15*v.stress,move:'Ask what choice you would make if starting fresh today.'}
];
function values(){let v={};ids.forEach(id=>v[id]=parseInt(document.getElementById(id).value));v.stakes=(v.loss+v.incentives)/2;return v}
function updateLabels(){ids.forEach(id=>document.getElementById(id+'Label').textContent=document.getElementById(id).value)}
function scores(){let v=values();return biasDefs.map(b=>({...b,score:Math.round(Math.max(0,Math.min(100,b.calc(v))))})).sort((a,b)=>b.score-a.score)}
function tag(score){if(score<40)return '<span class="tag-pill tag-low">Low</span>';if(score<70)return '<span class="tag-pill tag-med">Watch</span>';return '<span class="tag-pill tag-high">High</span>'}
function draw(){updateLabels();let v=values(),s=scores(),severity=Math.round(s.reduce((a,b)=>a+b.score,0)/s.length);ctx.clearRect(0,0,720,520);let grd=ctx.createRadialGradient(360,260,40,360,260,430);grd.addColorStop(0,`rgba(245,158,11,${.15+severity/170})`);grd.addColorStop(.55,`rgba(197,90,17,${.10+severity/260})`);grd.addColorStop(1,'rgba(31,78,121,.12)');ctx.fillStyle=grd;ctx.fillRect(0,0,720,520);for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(360,260,55+i*42,0,Math.PI*2);ctx.strokeStyle='rgba(100,116,139,.18)';ctx.stroke()}ctx.fillStyle='#102a43';ctx.font='bold 18px Arial';ctx.textAlign='center';ctx.fillText('Decision Weather',360,260);ctx.font='13px Arial';ctx.fillText('higher pressure = stronger shortcut pull',360,280);s.forEach((b,i)=>{let angle=-Math.PI/2+i*(Math.PI*2/s.length);let r=85+b.score*2.3;let x=360+Math.cos(angle)*r,y=260+Math.sin(angle)*r;ctx.beginPath();ctx.moveTo(360,260);ctx.lineTo(x,y);ctx.strokeStyle='rgba(31,78,121,.18)';ctx.stroke();ctx.beginPath();ctx.arc(x,y,16+b.score/10,0,Math.PI*2);ctx.fillStyle=b.score>70?'rgba(220,38,38,.78)':b.score>40?'rgba(245,158,11,.78)':'rgba(22,163,74,.72)';ctx.fill();ctx.fillStyle='#111827';ctx.font='bold 12px Arial';ctx.fillText(b.name,x,y-24);ctx.font='bold 13px Arial';ctx.fillStyle='white';ctx.fillText(b.score,x,y+4)});document.getElementById('severityMetric').textContent=severity;document.getElementById('dominantMetric').textContent=s[0].name;document.getElementById('riskMetric').textContent=severity<40?'Low':severity<70?'Watch':'High';let list=document.getElementById('biasList');list.innerHTML='';s.slice(0,5).forEach(b=>{list.innerHTML+=`<div class="bias-card"><b>${b.name}</b><span class="bias-score">${b.score}</span><div class="weather-meter"><div class="weather-fill" style="width:${b.score}%"></div></div><p class="small">${b.move}</p></div>`});document.getElementById('forecastShortcut').innerHTML=`${tag(s[0].score)} ${s[0].name} is the strongest pressure in this environment.`;document.getElementById('forecastMove').textContent=s[0].move;document.getElementById('forecastDebrief').textContent=`Ask how the environment increased ${s[0].name.toLowerCase()}, then redesign one condition before deciding.`}
ids.forEach(id=>document.getElementById(id).addEventListener('input',draw));document.getElementById('resetBtn').onclick=()=>{let defaults={stress:45,time:50,ambiguity:55,social:35,loss:60,incentives:45,confidence:55,delay:50};ids.forEach(id=>document.getElementById(id).value=defaults[id]);draw()};document.getElementById('stormBtn').onclick=()=>{let storm={stress:85,time:88,ambiguity:78,social:72,loss:90,incentives:82,confidence:80,delay:75};ids.forEach(id=>document.getElementById(id).value=storm[id]);draw()};draw();
