const $=id=>document.getElementById(id);let choice='stage';let tick=0;
const levels={clarity:v=>v<35?['Foggy signal','Evidence is thin. Assumptions dominate the map.']:v<70?['Mixed signal','Some evidence is available, but assumptions still matter.']:['Clearer signal','Evidence is relatively strong. Acting can be more justified.'],pressure:v=>v<35?['Open window','There is enough time to learn before committing.']:v<70?['Narrowing window','Waiting has a cost, but rushing can still damage the process.']:['Urgent window','Delay is costly. The decision may need action before comfort arrives.'],stakes:v=>v<35?['Reversible stakes','The consequences are modest or recoverable.']:v<70?['Meaningful stakes','The consequences matter enough to require explicit uncertainty.']:['High stakes','The cost of being wrong is significant. Process discipline matters.']};
function labelValue(id,spanId){const v=+$(id).value,[name,text]=levels[id](v);$(`${spanId}Level`).textContent=name.split(' ')[0]||name;return[v,name,text];}
function updateEnvironment(){const[c,cn,ct]=labelValue('clarity','clarity'),[p,pn,pt]=labelValue('pressure','pressure'),[s,sn,st]=labelValue('stakes','stakes');$('evidenceName').textContent=cn;$('evidenceText').textContent=ct;$('timingName').textContent=pn;$('timingText').textContent=pt;$('stakesName').textContent=sn;$('stakesText').textContent=st;$('forceLabel').textContent=`Environment: ${cn.toLowerCase()} · ${pn.toLowerCase()} · ${sn.toLowerCase()}`;$('fogMist').style.opacity=((100-c)/100*.72+.15).toFixed(2);return{clarity:c,pressure:p,stakes:s};}
function jitterPath(id,base,amp){const t=tick/22,j=Math.sin(t)*amp,k=Math.cos(t*.71)*amp;$(id).setAttribute('d',base(j,k));}
function animate(){tick++;jitterPath('lineCommit',(j,k)=>`M70 265 C180 ${220+j}, 286 ${188+k}, 410 ${168+j}`,3.6);jitterPath('lineStage',(j,k)=>`M70 248 C190 ${205+j}, 300 ${132+k}, 430 ${112+j}`,3.0);jitterPath('lineWait',(j,k)=>`M70 292 C185 ${350+k}, 290 ${392+j}, 422 ${404+k}`,3.6);jitterPath('outGG',(j,k)=>`M450 112 C520 ${88+k}, 610 ${100+j}, 700 ${132+k}`,2.6);jitterPath('outGB',(j,k)=>`M450 165 C530 ${180+k}, 620 ${192+j}, 700 ${210+k}`,2.6);jitterPath('outBG',(j,k)=>`M450 350 C528 ${318+k}, 612 ${312+j}, 700 ${292+k}`,2.6);jitterPath('outBB',(j,k)=>`M450 404 C530 ${430+k}, 615 ${416+j}, 700 ${384+k}`,2.6);requestAnimationFrame(animate);}requestAnimationFrame(animate);
function setChoice(c){choice=c;document.querySelectorAll('[data-choice]').forEach(b=>b.classList.toggle('selected',b.dataset.choice===c));document.querySelectorAll('.choice-card').forEach(x=>x.classList.remove('active-card'));$('card-'+c).classList.add('active-card');document.querySelectorAll('.decision-line').forEach(x=>x.classList.remove('active-path'));$('line'+c[0].toUpperCase()+c.slice(1)).classList.add('active-path');clearOutcome();}
function clearOutcome(){document.querySelectorAll('.branch-line').forEach(x=>x.classList.remove('active-branch'));document.querySelectorAll('.outcome-dot').forEach(x=>x.classList.remove('active-dot'));document.querySelectorAll('.outcome-card').forEach(x=>x.classList.remove('active-card'));$('outcomeToken').classList.remove('visible');}
function pathFit(env){const{clarity:c,pressure:p,stakes:s}=env;if(choice==='commit')return Math.max(0,Math.min(100,40+c*.42+p*.16-Math.max(0,55-c)*.32));if(choice==='stage')return Math.max(0,Math.min(100,58+(100-c)*.12+s*.08+((80-p)>0?6:-8)));return Math.max(0,Math.min(100,42+(100-c)*.06-p*.32-s*.08));}
function processScore(env){let prep=0;if($('assumption').checked)prep+=10;if($('unknown').checked)prep+=10;if($('trigger').checked)prep+=18;let randomProcess=(Math.random()*18)-9;return Math.round(Math.max(0,Math.min(100,30+prep+pathFit(env)*.42+randomProcess)));}
function outcome(env,proc){let environmentShock=(Math.random()*0.30)-0.15;let goodProb=.46+env.clarity*.0022+proc*.0014-env.stakes*.0012-Math.max(0,env.pressure-65)*.0018+environmentShock;if(choice==='stage')goodProb+=.03;if(choice==='wait'&&env.pressure>60)goodProb-=.11;if(choice==='commit'&&env.clarity<45)goodProb-=.10;goodProb=Math.max(.16,Math.min(.84,goodProb));const good=Math.random()<goodProb;const score=Math.round(good?52+Math.random()*38:12+Math.random()*42);return{good,score,prob:goodProb,shock:environmentShock};}
function roomKey(pg,og){return pg&&og?'gg':pg&&!og?'gb':!pg&&og?'bg':'bb'}
const roomLabels={gg:['Skill plus luck','Good process met a favorable outcome. Reinforce the process, but do not overcredit certainty.'],gb:['Discipline tested','The process was sound, but the world answered badly. Review assumptions without punishing good judgment.'],bg:['Luck disguised as wisdom','The outcome looked good, but the process was weak. This is the danger zone for overlearning.'],bb:['Failure with evidence','The process was weak and the outcome was bad. This is painful, but useful if the lesson is captured.']};
function explain(env,proc,out){const reasons=[],fit=Math.round(pathFit(env));reasons.push(`Path fit score: ${fit}. ${choice==='commit'?'Commit strengthens process when evidence is clear, but weakens when commitment outruns what is known.':choice==='stage'?'Stage preserves learning and generally moves the process upward.':'Wait can be wise only when time truly allows; otherwise it slides toward weak process.'}`);const prep=[];if($('assumption').checked)prep.push('assumption named');if($('unknown').checked)prep.push('unknown named');if($('trigger').checked)prep.push('update trigger named');reasons.push(prep.length?`Preparation visible: ${prep.join(', ')}.`:'Preparation was thin: the pre-outcome mind was not made visible.');if(env.clarity<35)reasons.push('Evidence clarity was low, so even a careful process still carried meaningful outcome risk.');if(env.pressure>70)reasons.push('Time pressure was high, making waiting costly and increasing downside exposure.');if(env.stakes>70)reasons.push('Stakes were high, increasing the cost of uncertainty.');reasons.push(`Outcome was ${out.good?'favorable':'unfavorable'}; estimated favorable-outcome chance was about ${Math.round(out.prob*100)}%.`);return reasons;}
function highlightOutcome(key){clearOutcome();const map={gg:['outGG','dotGG','oc-gg',715,132],gb:['outGB','dotGB','oc-gb',715,210],bg:['outBG','dotBG','oc-bg',715,292],bb:['outBB','dotBB','oc-bb',715,384]}[key];$(map[0]).classList.add('active-branch');$(map[1]).classList.add('active-dot');$(map[2]).classList.add('active-card');$('tokenCircle').setAttribute('cx',map[3]);$('tokenCircle').setAttribute('cy',map[4]);$('tokenText').setAttribute('x',map[3]);$('tokenText').setAttribute('y',map[4]+5);$('tokenText').textContent='RESULT';$('outcomeToken').classList.add('visible');}
function reveal(){const env=updateEnvironment(),proc=processScore(env),out=outcome(env,proc),pg=proc>=65,key=roomKey(pg,out.good);$('processScore').textContent=proc;$('processSub').innerHTML=pg?'<span class="good">Good process</span> before the ending.':'<span class="bad">Weak process</span> before the ending.';$('outcomeScore').textContent=out.score;$('outcomeSub').innerHTML=out.good?'<span class="good">Favorable outcome</span> in this run.':'<span class="bad">Unfavorable outcome</span> in this run.';$('roomName').textContent=roomLabels[key][0];$('roomSub').textContent=roomLabels[key][1];document.querySelectorAll('.room').forEach(r=>r.classList.remove('active'));$('room-'+key).classList.add('active');highlightOutcome(key);$('whyText').textContent=`This landed in “${roomLabels[key][0]}” because process quality and outcome quality are judged separately.`;$('whyList').innerHTML=explain(env,proc,out).map(x=>`<li>${x}</li>`).join('');}
document.querySelectorAll('[data-choice]').forEach(btn=>btn.addEventListener('click',()=>setChoice(btn.dataset.choice)));['clarity','pressure','stakes'].forEach(id=>$(id).addEventListener('input',()=>{updateEnvironment();clearOutcome();}));$('reveal').addEventListener('click',reveal);updateEnvironment();setChoice('stage');
